# Generated by Django 4.2.3 on 2023-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='must_finish_by',
            field=models.DateField(verbose_name='Date to be finished'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='pub_date',
            field=models.DateField(verbose_name='Date Published'),
        ),
    ]
